services:
  - type: web
    name: contentcal-backend
    env: node
    plan: free
    buildCommand: npm --prefix backend install
    startCommand: npm --prefix backend start
    envVars:
      - key: MONGODB_URI
        scope: run
        value: mongodb+srv://username:password@cluster.mongodb.net/calendario
      - key: NODE_ENV
        value: production
